services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  kafka-1:
    image: confluentinc/cp-kafka:7.6.0 # Pinned version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SSL,INTERNAL:SSL
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9092,INTERNAL://kafka-1:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/keys/kafka-broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEY_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12

      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/keys/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12

      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OPTS: "-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=7071:/etc/kafka/jmx_exporter/kafka-jmx.yml"
    volumes:
      - ./config/kafka-exporter:/etc/kafka/jmx_exporter
      - ./keys/artifacts:/etc/kafka/keys

  kafka-2:
    image: confluentinc/cp-kafka:7.6.0 # Pinned version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SSL,INTERNAL:SSL
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9093,INTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9093,INTERNAL://kafka-2:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/keys/kafka-broker2.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEY_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12

      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/keys/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12

      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OPTS: "-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=7071:/etc/kafka/jmx_exporter/kafka-jmx.yml"
    volumes:
      - ./config/kafka-exporter:/etc/kafka/jmx_exporter
      - ./keys/artifacts:/etc/kafka/keys

  kafka-3:
    image: confluentinc/cp-kafka:7.6.0 # Pinned version
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SSL,INTERNAL:SSL
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9094,INTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9094,INTERNAL://kafka-3:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/keys/kafka-broker3.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEY_PASSWORD: YourStrongPassword!
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12

      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/keys/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: YourStrongPassword!
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12

      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OPTS: "-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=7071:/etc/kafka/jmx_exporter/kafka-jmx.yml"
    volumes:
      - ./config/kafka-exporter:/etc/kafka/jmx_exporter
      - ./keys/artifacts:/etc/kafka/keys

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19092,kafka-3:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181

      KAFKA_CLUSTERS_0_PROPERTIES_security_protocol: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_ssl_truststore_location: /etc/kafka/keys/kafka.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_ssl_truststore_password: YourStrongPassword!
      KAFKA_CLUSTERS_0_PROPERTIES_ssl_truststore_type: PKCS12
      KAFKA_CLUSTERS_0_PROPERTIES_ssl_endpoint_identification_algorithm: https
    volumes:
      - ./keys/artifacts:/etc/kafka/keys

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9308:9308"
    command:
      - --kafka.server=kafka-1:19092
      - --kafka.server=kafka-2:19092
      - --kafka.server=kafka-3:19092
      - --web.listen-address=:9308
      - --tls.enabled
      - --tls.ca-file=/etc/kafka/keys/ca.crt
      - --tls.cert-file=/etc/kafka/keys/kafka-exporter.crt
      - --tls.key-file=/etc/kafka/keys/kafka-exporter.key
    volumes:
      - ./keys/artifacts:/etc/kafka/keys

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - kafka-exporter
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data: