global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7072', 'kafka-3:7073']
        labels:
          instance: 'kafka'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          instance: 'kafka-exporter'